/**
 * Research Agent
 *
 * Specializes in deep research:
 * - Guest background and recent work
 * - Topic preparation and talking points
 * - Competitive podcast landscape
 * - Industry trends
 */

import Anthropic from '@anthropic-ai/sdk';
import { runAgent, runSimpleAgent, logAgentActivity, type AgentConfig, type AgentResult } from './base-agent.js';
import { GUESTS } from '../data/guests.js';
import { BRAND, EPISODE_FORMAT, RAPID_FIRE_QUESTIONS } from '../config.js';

// Tool definitions
const RESEARCH_TOOLS: Anthropic.Tool[] = [
  {
    name: 'get_guest_context',
    description: 'Get stored context about a guest from our database',
    input_schema: {
      type: 'object' as const,
      properties: {
        name: {
          type: 'string',
          description: 'Guest name'
        }
      },
      required: ['name']
    }
  },
  {
    name: 'get_episode_format',
    description: 'Get the standard episode format and segments',
    input_schema: {
      type: 'object' as const,
      properties: {},
      required: []
    }
  },
  {
    name: 'get_rapid_fire_questions',
    description: 'Get the pool of rapid fire questions',
    input_schema: {
      type: 'object' as const,
      properties: {},
      required: []
    }
  },
  {
    name: 'compile_research',
    description: 'Compile research findings into a structured brief',
    input_schema: {
      type: 'object' as const,
      properties: {
        guestName: {
          type: 'string',
          description: 'Guest name'
        },
        findings: {
          type: 'string',
          description: 'Research findings to compile'
        },
        talkingPoints: {
          type: 'array',
          items: { type: 'string' },
          description: 'List of talking points'
        }
      },
      required: ['guestName', 'findings']
    }
  }
];

// Tool handler
async function handleToolCall(
  toolName: string,
  toolInput: Record<string, unknown>
): Promise<string> {
  logAgentActivity('ResearchAgent', 'tool_call', toolName);

  switch (toolName) {
    case 'get_guest_context': {
      const name = toolInput.name as string;
      const guest = GUESTS.find(g =>
        g.name.toLowerCase().includes(name.toLowerCase())
      );

      if (!guest) {
        return JSON.stringify({ error: `Guest "${name}" not in database`, suggestion: 'Research them from scratch' });
      }

      return JSON.stringify({
        name: guest.name,
        twitter: guest.twitter,
        farcaster: guest.farcaster,
        whoTheyAre: guest.whoTheyAre,
        why: guest.why,
        suggestedTopics: guest.topics,
        contactStrategy: guest.contactStrategy,
        notes: guest.notes
      });
    }

    case 'get_episode_format': {
      return JSON.stringify({
        duration: EPISODE_FORMAT.duration,
        segments: EPISODE_FORMAT.segments,
        note: 'Main conversation (35-45 min) should follow curiosity naturally'
      });
    }

    case 'get_rapid_fire_questions': {
      return JSON.stringify({
        questions: RAPID_FIRE_QUESTIONS,
        note: 'Pick 3-5 that fit the guest. Can also improvise.'
      });
    }

    case 'compile_research': {
      const guestName = toolInput.guestName as string;
      const findings = toolInput.findings as string;
      const talkingPoints = toolInput.talkingPoints as string[] | undefined;

      const brief = `
# Research Brief: ${guestName}

## Background
${findings}

## Talking Points
${talkingPoints?.map((tp, i) => `${i + 1}. ${tp}`).join('\n') || 'To be developed'}

## Episode Fit
- Format: ${EPISODE_FORMAT.duration.min}-${EPISODE_FORMAT.duration.max} min conversation
- Segments: Cold open, intro, guest intro, main convo, rapid fire, outro

## Rapid Fire Options
${RAPID_FIRE_QUESTIONS.slice(0, 5).map(q => `- ${q}`).join('\n')}

---
*Generated by Research Agent for ${BRAND.name}*
`;

      return JSON.stringify({
        compiled: true,
        brief,
        wordCount: brief.split(/\s+/).length
      });
    }

    default:
      return JSON.stringify({ error: `Unknown tool: ${toolName}` });
  }
}

// Agent configuration
const RESEARCH_AGENT_CONFIG: AgentConfig = {
  name: 'ResearchAgent',
  description: 'Deep research and episode preparation specialist',
  systemPrompt: `You are the Research Agent for Let's Vibe! podcast.

Your job is to prepare hosts for great conversations through thorough research.

Responsibilities:
1. Research guest backgrounds, recent work, and hot takes
2. Identify interesting angles and talking points
3. Find potential controversies or sensitive topics to navigate
4. Create pre-recording briefs
5. Track industry trends relevant to episodes

Research approach:
- Go beyond Wikipedia basics - find recent interviews, tweets, projects
- Look for contrarian takes or interesting opinions
- Find overlap between guest's work and vibe coding/AI creativity
- Note any connections to our network (NODE, Spirit, Eden)

Output format:
- Structured briefs with clear sections
- Specific, actionable talking points
- Suggested questions, not vague topics

Remember: The goal is to help Seth and Lukas have natural, curious conversations - not scripted interviews.`,
  tools: RESEARCH_TOOLS
};

/**
 * Run the research agent with a specific task
 */
export async function runResearchAgent(task: string): Promise<AgentResult> {
  logAgentActivity('ResearchAgent', 'starting', task.slice(0, 50));
  const result = await runAgent(RESEARCH_AGENT_CONFIG, task, handleToolCall);
  logAgentActivity('ResearchAgent', result.success ? 'completed' : 'failed');
  return result;
}

/**
 * Quick helper: Research a guest
 */
export async function researchGuest(guestName: string): Promise<AgentResult> {
  return runResearchAgent(`
Research ${guestName} for an upcoming episode.

Include:
1. Who they are (background, current work)
2. Recent activity (last 3-6 months)
3. Their perspective on AI/creativity
4. Potential talking points
5. Things to avoid or be careful about
6. Suggested questions

Use get_guest_context first to see what we already know.
`);
}

/**
 * Quick helper: Prepare talking points
 */
export async function prepareTalkingPoints(guestName: string, focusArea?: string): Promise<AgentResult> {
  const task = focusArea
    ? `Prepare talking points for ${guestName} focused on: ${focusArea}`
    : `Prepare 7-10 talking points for our conversation with ${guestName}`;

  return runResearchAgent(task);
}

/**
 * Quick helper: Competitive research
 */
export async function researchCompetitors(): Promise<AgentResult> {
  return runSimpleAgent(
    RESEARCH_AGENT_CONFIG.systemPrompt,
    `Research the competitive podcast landscape for Let's Vibe!

Focus on:
1. Latent Space (swyx) - technical AI
2. AI Breakdown - news focused
3. Hard Fork (NYT) - tech/business
4. Dwarkesh Podcast - deep interviews

For each:
- What's their angle?
- Who's their audience?
- What can we learn?
- How do we differentiate?

Our positioning: Vibecoding for CREATIVES, not developers.`
  );
}

/**
 * Quick helper: Trend research
 */
export async function researchTrends(topic?: string): Promise<AgentResult> {
  const focusTopic = topic || 'vibe coding and AI creativity';
  return runSimpleAgent(
    RESEARCH_AGENT_CONFIG.systemPrompt,
    `What are the current trends and hot topics in ${focusTopic}?

Consider:
1. Recent tools and releases
2. Debates and controversies
3. Viral moments
4. Emerging voices
5. What our potential guests are saying

Format as a trend brief we can reference when planning episodes.`
  );
}

// CLI execution
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const task = args.join(' ') || 'Research trends in vibe coding';

  console.log('🔬 Research Agent');
  console.log('=================\n');

  runResearchAgent(task).then(result => {
    if (result.success) {
      console.log(result.output);
      if (result.toolsUsed.length > 0) {
        console.log(`\n[Tools used: ${result.toolsUsed.join(', ')}]`);
      }
    } else {
      console.error('Error:', result.error);
    }
  });
}
