-- Seed Episode 1: The Netscape Moment
INSERT INTO episodes (
  number,
  slug,
  title,
  description,
  status,
  guest_name,
  guest_handle,
  guest_bio,
  date,
  duration,
  spotify_url,
  apple_url,
  youtube_url,
  show_notes,
  topics,
  chapters,
  links
) VALUES (
  1,
  'the-netscape-moment',
  'The Netscape Moment',
  'Seth and Ian kick off the show with the origin story. 30 years of building, imposter syndrome, the Oliver Sacks piano analogy, and why the terminal is the future.',
  'published',
  'Seth Goldstein & Ian Rogers',
  '@seth & @iancr',
  'Seth is building /vibe, a social layer for Claude Code. Ian is CXO of Ledger, former CDO at LVMH, and built Beats Music. Together they have 30 years of building on the internet.',
  'Jan 27, 2026',
  '48 min',
  'https://open.spotify.com/episode/29Du7dKES9PK5Gmu0RnHrY',
  'https://podcasts.apple.com/us/podcast/lets-vibe/id1873355247',
  'https://youtu.be/1kWtAUDdvJc',
  E'Two seasoned tech veterans reflect on 30 years of building and how it prepared them for the AI revolution we''re living through right now.\n\nIan, who studied computer science, reflects on his shift from coding to management — and his recent obsession with AI coding. Seth shares his journey from starting his first company in 1995 to working at Epicurious.com as an HTML programmer, and the awe he felt at the launch of Netscape, which he describes as a "Big Bang moment" for the web.\n\nThe conversation draws parallels between the internet boom and today''s AI revolution. Both agree that while people may overestimate the immediate effects of AI, the long-term implications could be far greater than anticipated — echoing their experiences during the rise of the internet, where initial skepticism gave way to profound societal changes.\n\nSeth draws an analogy to Oliver Sacks'' stories, illustrating the feeling of suddenly unlocking new abilities, akin to playing an instrument without prior training. He expresses a mix of pride and imposter syndrome navigating AI without a formal coding background. Ian adds that the current era feels similar to the democratization of music production in the 90s, where barriers to entry were lowered, allowing more creativity and innovation.\n\n"The future is already here — it''s just not evenly distributed."',
  ARRAY['Origin story', 'Vibe coding', 'Creative process'],
  '[
    {"time": "0:00", "title": "Introduction — The Beginning of a New Era"},
    {"time": "4:00", "title": "Netscape: The Big Bang of the Internet"},
    {"time": "8:00", "title": "Seth''s Journey: From HTML to AI"},
    {"time": "14:00", "title": "AI''s Greatest Bubble: Overestimating Short-Term, Underestimating Long-Term"},
    {"time": "20:00", "title": "The Rise and Fall of Turntable.fm"},
    {"time": "26:00", "title": "Command Line: Past, Present, Future with AI"},
    {"time": "32:00", "title": "A 55-Year-Old''s Unlikely Piano Journey (Oliver Sacks)"},
    {"time": "38:00", "title": "The Evolution of Music & Code Distribution"},
    {"time": "44:00", "title": "Bright Moments: A Full Circle Journey"}
  ]'::jsonb,
  '[
    {"label": "Proof of Corn", "url": "https://proofofcorn.com"},
    {"label": "/vibe — Social layer for Claude Code", "url": "https://slashvibe.dev"},
    {"label": "Ian''s blog: Reflections on a Claude Code New Year", "url": "https://fistfulayen.com/2026/01/13/reflections-on-a-claude-code-new-year/"},
    {"label": "Karpathy''s \"vibe coding\" post", "url": "https://x.com/karpathy/status/1886192184808149383"},
    {"label": "Episode 1 prep notes", "url": "/prep/farmer-fred"}
  ]'::jsonb
) ON CONFLICT (number) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  guest_name = EXCLUDED.guest_name,
  guest_handle = EXCLUDED.guest_handle,
  guest_bio = EXCLUDED.guest_bio,
  date = EXCLUDED.date,
  duration = EXCLUDED.duration,
  spotify_url = EXCLUDED.spotify_url,
  apple_url = EXCLUDED.apple_url,
  youtube_url = EXCLUDED.youtube_url,
  show_notes = EXCLUDED.show_notes,
  topics = EXCLUDED.topics,
  chapters = EXCLUDED.chapters,
  links = EXCLUDED.links,
  updated_at = NOW();

-- Seed Episode 2: Seth Interviews Ian (upcoming)
INSERT INTO episodes (
  number,
  slug,
  title,
  description,
  status,
  guest_name,
  guest_handle,
  guest_bio,
  date,
  duration,
  show_notes,
  topics,
  chapters,
  links
) VALUES (
  2,
  'seth-interviews-ian',
  'Seth Interviews Ian',
  E'Seth turns the tables and interviews Ian. The Rick Rubin vibe code story, Ian''s journey building, the Pro Tools parallel, and why a BA in Computer Science predicted this moment. Plus: OpenClaw 101 — practical advice on getting started.',
  'upcoming',
  'Ian Rogers',
  '@iancr',
  E'CXO of Ledger. He interviewed Rick Rubin on Tetragrammaton about "The Way of Code." Texts with Rick daily about vibe coding. For the full arc (Topspin, Beats, LVMH), see the Tetragrammaton interviews.',
  'Feb 6, 2026',
  'TBD',
  E'Seth interviews Ian Rogers — but lighter on the full bio arc. For the long version (Topspin, Beats Music, LVMH), check out Ian''s Tetragrammaton interviews with Rick Rubin and The Monty Report.\n\n**The Rick Rubin Story**: Ian interviewed Rick on Tetragrammaton about "The Way of Code." Rick texts Ian every day about vibe coding. What does Rick say that he says best? What is Rick actually building?\n\n**Ian''s Journey Building**: A CS degree holder who spent decades as an executive, now coding again. The Claude Code New Year: RSVP systems, art galleries, and music projects shipped with "minimal keyboard time." First music project since leaving Apple Music 10+ years ago.\n\n**The Analogies**: The Pro Tools parallel — Ian was actually there for that revolution. The BA in Computer Science — a degree that doesn''t exist anymore predicted the future of computing: creativity first, code second.\n\n**Tutorial: OpenClaw 101**: Practical advice on setting up OpenClaw. Do you want to do it? Why should you? Why shouldn''t you? How far should you go? What are the pitfalls? What are the use cases?',
  ARRAY['Rick Rubin', 'Vibe Coding', 'OpenClaw', 'Pro Tools Parallel'],
  '[
    {"time": "0:00", "title": "Turn the Tables — Seth interviews Ian"},
    {"time": "5:00", "title": "The Rick Rubin Vibe Code Story"},
    {"time": "15:00", "title": "Ian''s Journey Building"},
    {"time": "25:00", "title": "The Pro Tools Parallel"},
    {"time": "35:00", "title": "The Analogies"},
    {"time": "45:00", "title": "Tutorial: OpenClaw 101"}
  ]'::jsonb,
  '[
    {"label": "Ian''s Tetragrammaton interview with Rick Rubin", "url": "https://www.tetragrammaton.com/ian-rogers"},
    {"label": "Ian''s blog: Reflections on a Claude Code New Year", "url": "https://fistfulayen.com/2026/01/13/reflections-on-a-claude-code-new-year/"},
    {"label": "Ian on X", "url": "https://x.com/iancr"},
    {"label": "Episode 2 prep notes", "url": "/prep/episode-2"},
    {"label": "OpenClaw 101 plan", "url": "/plan/ep2"}
  ]'::jsonb
) ON CONFLICT (number) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  guest_name = EXCLUDED.guest_name,
  guest_handle = EXCLUDED.guest_handle,
  guest_bio = EXCLUDED.guest_bio,
  date = EXCLUDED.date,
  duration = EXCLUDED.duration,
  show_notes = EXCLUDED.show_notes,
  topics = EXCLUDED.topics,
  chapters = EXCLUDED.chapters,
  links = EXCLUDED.links,
  updated_at = NOW();
