-- Let's Vibe! Studio — Episode, clip, guest, transcript, and social tables
-- Run in Supabase SQL Editor to deploy

-- Drop old empty tables from schema.sql (they have no data, missing new columns)
DROP TABLE IF EXISTS clips CASCADE;
DROP TABLE IF EXISTS guests CASCADE;
DROP TABLE IF EXISTS episodes CASCADE;

-- Episodes (extended with slug, show_notes_html, chapters, quotes, links)
CREATE TABLE episodes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  number INT NOT NULL,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  guest_name TEXT,
  guest_bio TEXT,
  guest_twitter TEXT,
  date TEXT, -- display date like "January 30, 2026"
  duration TEXT, -- display duration like "52 min"
  recorded_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  duration_seconds INT,

  -- URLs
  audio_url TEXT,
  video_url TEXT,
  youtube_url TEXT,
  spotify_url TEXT,
  apple_url TEXT,

  -- Rich content (generated by AI, stored as JSON)
  show_notes TEXT,
  show_notes_html TEXT,
  chapters JSONB DEFAULT '[]'::jsonb,
  quotes JSONB DEFAULT '[]'::jsonb,
  links JSONB DEFAULT '[]'::jsonb,

  -- Status
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'recorded', 'editing', 'published')),

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Clips (viral moments from episodes)
CREATE TABLE clips (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  episode_id UUID REFERENCES episodes(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  start_time INT NOT NULL, -- seconds
  end_time INT NOT NULL,
  transcript_excerpt TEXT,
  topic TEXT,

  -- URLs
  video_url TEXT,
  tiktok_url TEXT,
  twitter_url TEXT,

  -- AI suggestions
  virality_score FLOAT,
  suggested_caption TEXT,
  platform TEXT CHECK (platform IN ('youtube-shorts', 'tiktok', 'twitter', 'instagram')),

  status TEXT DEFAULT 'suggested' CHECK (status IN ('suggested', 'approved', 'exported', 'published')),

  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Guests (pipeline/CRM)
CREATE TABLE guests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  twitter TEXT,
  farcaster TEXT,
  email TEXT,
  company TEXT,
  role TEXT,
  bio TEXT,
  tier INT CHECK (tier BETWEEN 0 AND 6),
  category TEXT,
  topics TEXT[],
  notes TEXT,
  why TEXT,
  contact_strategy TEXT,

  -- Outreach tracking
  outreach_status TEXT DEFAULT 'wishlist' CHECK (outreach_status IN ('wishlist', 'contacted', 'confirmed', 'scheduled', 'recorded', 'published', 'declined')),
  contacted_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  episode_id UUID REFERENCES episodes(id),

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Transcripts (full text + speaker segments)
CREATE TABLE transcripts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  episode_id UUID REFERENCES episodes(id) ON DELETE CASCADE UNIQUE,
  full_text TEXT NOT NULL,
  speaker_segments JSONB DEFAULT '[]'::jsonb,
  source TEXT DEFAULT 'manual', -- manual, riverside, descript
  word_count INT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Social posts (drafts, scheduled, posted)
CREATE TABLE social_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  episode_id UUID REFERENCES episodes(id) ON DELETE CASCADE,
  clip_id UUID REFERENCES clips(id) ON DELETE SET NULL,
  platform TEXT NOT NULL CHECK (platform IN ('x', 'farcaster', 'youtube', 'instagram', 'tiktok')),
  post_type TEXT DEFAULT 'post' CHECK (post_type IN ('post', 'thread', 'announcement', 'clip', 'quote')),
  content TEXT NOT NULL,
  media_urls JSONB DEFAULT '[]'::jsonb,
  scheduled_for TIMESTAMPTZ,
  posted_at TIMESTAMPTZ,
  external_post_id TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'scheduled', 'posted', 'failed')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE clips ENABLE ROW LEVEL SECURITY;
ALTER TABLE guests ENABLE ROW LEVEL SECURITY;
ALTER TABLE transcripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE social_posts ENABLE ROW LEVEL SECURITY;

-- RLS Policies: public read for published content, service_role for writes
CREATE POLICY "Public can view published episodes" ON episodes
  FOR SELECT USING (status = 'published');

CREATE POLICY "Service role full access to episodes" ON episodes
  FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Public can view approved clips" ON clips
  FOR SELECT USING (status IN ('approved', 'exported', 'published'));

CREATE POLICY "Service role full access to clips" ON clips
  FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Service role full access to guests" ON guests
  FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Service role full access to transcripts" ON transcripts
  FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Public can view posted social_posts" ON social_posts
  FOR SELECT USING (status = 'posted');

CREATE POLICY "Service role full access to social_posts" ON social_posts
  FOR ALL USING (auth.role() = 'service_role');

-- Indexes
CREATE INDEX episodes_slug_idx ON episodes(slug);
CREATE INDEX episodes_status_idx ON episodes(status);
CREATE INDEX episodes_published_at_idx ON episodes(published_at DESC);
CREATE INDEX episodes_number_idx ON episodes(number DESC);
CREATE INDEX clips_episode_id_idx ON clips(episode_id);
CREATE INDEX clips_status_idx ON clips(status);
CREATE INDEX guests_tier_idx ON guests(tier);
CREATE INDEX guests_outreach_status_idx ON guests(outreach_status);
CREATE INDEX transcripts_episode_id_idx ON transcripts(episode_id);
CREATE INDEX social_posts_episode_id_idx ON social_posts(episode_id);
CREATE INDEX social_posts_status_idx ON social_posts(status);
CREATE INDEX social_posts_platform_idx ON social_posts(platform);

-- Auto-update triggers for updated_at
CREATE TRIGGER update_episodes_updated_at
  BEFORE UPDATE ON episodes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_guests_updated_at
  BEFORE UPDATE ON guests
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_transcripts_updated_at
  BEFORE UPDATE ON transcripts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_social_posts_updated_at
  BEFORE UPDATE ON social_posts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
